$schema: "http://json-schema.org/draft-04/schema#"

id: "environment"
title: Environment
type: object
nodeTerms: null
namespace: http://gdc.nci.nih.gov
category: administrative
program: '*'
project: '*'
description: The collection of all data related to a specific environment in the context
  of a specific project.
additionalProperties: false
submittable: true
validators: null

systemProperties:
  - id
  - project_id
  - state
  - created_datetime
  - updated_datetime

links:
  - name: centers
    backref: Environments
    label: recruited_at
    target_type: center
    multiplicity: many_to_one
    required: true

required:
  - submitter_id
  - type
  - centers

uniqueKeys:
  - [id]
  - [project_id, submitter_id]

properties:

  $ref: "_definitions.yaml#/ubiquitous_properties"

  order_detailed:
    description: tbd
    type: integer

  other_id:
    description: tbd
    type: integer

  product_id:
    description: tbd
    type: integer

  product_quantity:
    description: tbd
    type: integer

  centers:
    $ref: "_definitions.yaml#/to_one"
